#!/usr/bin/env bash
# Run format code generators from repo root.
#
# MEI: generates tusk-model + tusk-mei serializer/deserializer impls from RNG.
# MusicXML: generates data types from main XSD (4.1). Versioned models (2.0–4.0)
#   are generated automatically by tusk-musicxml's build.rs when you build that crate.
#
# Usage: ./scripts/run-codegen.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

echo "=== MEI codegen (RNG → tusk-model + tusk-mei impls) ==="
cargo run -p tusk-mei-codegen -- \
  --rng specs/mei/validation/mei-all.rng \
  --output crates/core/model/src/generated \
  --mei-crate crates/formats/mei/src

echo ""
echo "=== MusicXML codegen (main XSD 4.1 → data types only) ==="
echo "For manual run; versioned (2.0–4.0) are generated by tusk-musicxml build.rs."
cargo run -p tusk-musicxml-codegen -- \
  --input specs/musicxml/schema/musicxml.xsd \
  --output /tmp/musicxml-codegen-out

echo ""
echo "Codegen done. Run 'cargo build' to regenerate MusicXML versioned modules."