#!/usr/bin/env bash
# Run format code generators from repo root.
#
# MEI: generates tusk-model + tusk-mei serializer/deserializer impls from RNG.
# MusicXML: versioned models (2.0–4.1) are generated by tusk-musicxml's build.rs
#   when you build that crate. The script below is for manual codegen run only.
#
# Usage: ./scripts/run-codegen.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

echo "=== MEI codegen (RNG → tusk-model + tusk-mei impls) ==="
cargo run -p tusk-mei-codegen -- \
  --rng crates/formats/mei/codegen/schema/versions/mei-all_v6.0-dev.rng \
  --output crates/core/model/src/generated \
  --mei-crate crates/formats/mei/src

echo ""
echo "=== MusicXML codegen (optional manual run) ==="
echo "Versioned models (2.0–4.1) are generated by tusk-musicxml build.rs on cargo build."
cargo run -p tusk-musicxml-codegen -- \
  --input crates/formats/musicxml/codegen/schema/versions/musicxml-4.1/schema/musicxml.xsd \
  --output /tmp/musicxml-codegen-out

echo ""
echo "Codegen done."